/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoviesSlugRouteImport } from './routes/movies.$slug'

const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesSlugRoute = MoviesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MoviesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/movies': typeof MoviesRouteWithChildren
  '/movies/$slug': typeof MoviesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/movies': typeof MoviesRouteWithChildren
  '/movies/$slug': typeof MoviesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/movies': typeof MoviesRouteWithChildren
  '/movies/$slug': typeof MoviesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/characters' | '/movies' | '/movies/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/characters' | '/movies' | '/movies/$slug'
  id: '__root__' | '/' | '/characters' | '/movies' | '/movies/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersRoute: typeof CharactersRoute
  MoviesRoute: typeof MoviesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$slug': {
      id: '/movies/$slug'
      path: '/$slug'
      fullPath: '/movies/$slug'
      preLoaderRoute: typeof MoviesSlugRouteImport
      parentRoute: typeof MoviesRoute
    }
  }
}

interface MoviesRouteChildren {
  MoviesSlugRoute: typeof MoviesSlugRoute
}

const MoviesRouteChildren: MoviesRouteChildren = {
  MoviesSlugRoute: MoviesSlugRoute,
}

const MoviesRouteWithChildren =
  MoviesRoute._addFileChildren(MoviesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersRoute: CharactersRoute,
  MoviesRoute: MoviesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
